### PR TITLE
feat: configure client certificate mode

### PR DESCRIPTION
**Pull request by kov117**
### Checklist

- [x] I've updated both the `azurerm_linux_function_app` and `azurerm_windows_function_app` resources.

### CODE REVIEW

**Comment by kov117** [comment]
Test pass 🎆

**Comment by kov117** [comment]
agreed and appreciated for the heads up 🫶

**Comment by kov117** [comment]
Ran a new test and it passed 👍🏼

**Comment by kov117** [comment]
Passed the test 👍🏼

**Comment by hknutsen** [comment]
I think this looks good now, however the `client_certificate_mode` argument has no effect without the `client_certificate_enabled` argument. We should have a variable for that as well (see link to relevant PR in my [previous comment](https://github.com/equinor/terraform-azurerm-function-app/pull/80#issuecomment-2491308045)).

**Comment by kov117** [comment]
Noted, should i include it to the tftest config as well ?

**Comment by hknutsen** [comment]
> Noted, should i include it to the tftest config as well ?

I think yes 👍

**Comment by kov117** [comment]
Test passed 👍🏼

**Review by hknutsen — DISMISSED** [review]

**Comment by hknutsen** [comment]
@kov117 some of the `windows_client_certificate_*` tests refer to the `azurerm_linux_function_app` resource.

**Comment by kov117** [comment]
Terraform test passed 👍🏼

**Review by hknutsen — APPROVED** [review]
Looks good 👍

**Pull request merged**
